version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_REALM=myrealm
      - KEYCLOAK_CLIENT_ID=myclient
    ports:
      - "8080:8080"
    command: ["start-dev"]
